// server/src/config/constants.js
// All application-wide enums and status values.
// OWNER: Member 1 — PR required before changing any enum value.
// Keep in sync with client/src/utils/constants.js

const ROLES = Object.freeze({
  MEMBER: 'MEMBER',
  COMMUNITY_ADMIN: 'COMMUNITY_ADMIN',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
});

const MEMBERSHIP_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
});

const COMMUTE_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

const BOOKING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
});

const RIDE_REQUEST_STATUS = Object.freeze({
  OPEN: 'OPEN',
  OFFER_RECEIVED: 'OFFER_RECEIVED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

const RIDE_OFFER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
});

const CONTRIBUTION_PROPOSAL_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
});

const VEHICLE_TYPE = Object.freeze({
  BIKE: 'BIKE',
  CAR: 'CAR',
});

const REPORT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
});

const NOTIFICATION_TYPE = Object.freeze({
  BOOKING_REQUEST: 'BOOKING_REQUEST',
  BOOKING_ACCEPTED: 'BOOKING_ACCEPTED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  OFFER_RECEIVED: 'OFFER_RECEIVED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  CONTRIBUTION_PROPOSAL: 'CONTRIBUTION_PROPOSAL',
  CONTRIBUTION_ACCEPTED: 'CONTRIBUTION_ACCEPTED',
  CONTRIBUTION_REJECTED: 'CONTRIBUTION_REJECTED',
  COMMUTE_REMINDER: 'COMMUTE_REMINDER',
  TRIP_STATUS_UPDATE: 'TRIP_STATUS_UPDATE',
});

module.exports = {
  ROLES,
  MEMBERSHIP_STATUS,
  COMMUTE_STATUS,
  BOOKING_STATUS,
  RIDE_REQUEST_STATUS,
  RIDE_OFFER_STATUS,
  CONTRIBUTION_PROPOSAL_STATUS,
  VEHICLE_TYPE,
  REPORT_STATUS,
  NOTIFICATION_TYPE,
};
